# Generated by Django 4.2.30 on 2026-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_allergies_user_height_cm_user_is_onboarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diseases',
            field=models.TextField(blank=True),
        ),
    ]
