# Generated by Django 4.2.30 on 2026-05-28 16:17

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_age_user_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_onboarded',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight_kg',
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to=core.models.user_image_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='health_profiles', to='core.allergy')),
                ('diseases', models.ManyToManyField(blank=True, related_name='health_profiles', to='core.disease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healthprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
