# Generated by Django 4.2.30 on 2026-05-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_allergy_disease_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='last_suggested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='last_suggested_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_profiles', to='core.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_liked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
