FROM python:3.10-slim
ENV PYTHONUNBUFFERED=1

# Install system dependencies (ffmpeg is required by faster-whisper)
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Install python packages
RUN pip install --no-cache-dir --default-timeout=1000 --retries 10 fastapi uvicorn faster-whisper python-multipart requests

# Copy service code
COPY ./whisper_app /app
WORKDIR /app

EXPOSE 9000

# Run uvicorn server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
